#include "pool-names.hpp"

constexpr MinerAlias kScriptSigAliases[] = {
   {"shawnp0wers", "--nug--"},
   {"7pool", "mined by 7pool.com"},
   {"1THash", "1thash&58coin"},
   {"1THash", "1thash"},
   {"Foundry USA", "2cdw"},
   {"Foundry USA", "foundry usa"},
   {"58COIN", "58coin.com"},
   {"A-XBT", "a-xbt"},
   {"AAO Pool", "aaopool"},
   {"AntPool", "antpool"},
   {"ArkPool", "arkpool"},
   {"BATPOOL", "batpool"},
   {"BCMonster", "bcmonster"},
   {"BTC.com", "btc.com"},
   {"BTC.com", "btccom"},
   {"BTC.TOP", "btc.top"},
   {"BTCC", "btcc"},
   {"BTCC", "btcchina"},
   {"BTPOOL", "btpool"},
   {"Binance Pool", "binance"},
   {"Binance Pool", "binance.com/"},
   {"BitClub", "bitclub network"},
   {"BitFury", "bitfury"},
   {"BitcoinIndia", "bitcoin-india"},
   {"BitcoinRussia", "bitcoin-russia.ru"},
   {"Bitcoin-Ukraine", "bitcoin-ukraine.com.ua"},
   {"Bixin", "bixin"},
   {"Bixin", "haobtc"},
   {"Lubian.com", "buffett"},
   {"CanoePool", "canoe"},
   {"CanoePool", "canoepool"},
   {"ConnectBTC", "connectbtc - home for miners"},
   {"DCEX", "dcex"},
   {"DCExploration", "dcexploitation"},
   {"DPOOL", "dpool.top"},
   {"WAYI.CN", "e2m & btc.top"},
   {"WAYI.CN", "e2m"},
   {"EMCDPool", "emcd"},
   {"EMCDPool", "one_more_mcd"},
   {"EMCDPool", "emcd.io"},
   {"EMCDPool", "get___emcd"},
   {"Helix", "helix"},
   {"HotPool", "hotpool"},
   {"Huobi Pool", "huobi"},
   {"Huobi Pool", "huobi"},
   {"Luxor", "luxor"},
   {"Luxor", "luxor tech"},
   {"MARA Pool", "mara pool"},
   {"MARA Pool", "mara made in usa"},
   {"MaxiPool", "maxipool"},
   {"HashBX", "mined by hashbx.io"},
   {"Minerium", "minerium.com"},
   {"Mining-Dutch", "mining-dutch"},
   {"Nexious", "nexious"},
   {"NiceHash", "nicehash"},
   {"NiceHash", "nicehashmining"},
   {"NiceHash", "nicehashsolo"},
   {"NovaBlock", "novablock"},
   {"Rawpool", "rawpool.com"},
   {"RigPool", "rigpool.com"},
   {"SBI Crypto", "sbicrypto.com pool"},
   {"SBI Crypto", "sbi crypto"},
   {"SBI Crypto", "sbicrypto"},
   {"SecretSuperstar", "secretsuperstar"},
   {"Sigmapool.com", "sigmapool.com"},
   {"TMSPool", "tmspool"},
   {"Tangpool", "tangpool"},
   {"ViaBTC", "viabtc/tatmas pool"},
   {"ViaBTC", "viabtc"},
   {"ViaBTC", "viabtc.com deploy"},
   {"TATMAS Pool", "tatmas pool"},
   {"Waterhole", "waterhole.io"},
   {"digitalBTC", "agentd"},
   {"Bravo Mining", "bravo-mining"},
   {"BytePool", "bytepool.com"},
   {"CKPool", "ckpool.org"},
   {"CKPool", "ckpool"},
   {"haominer", "haominer"},
   {"HAOZHUZHU", "haozhuzhu"},
   {"OKKONG", "hash.okkong.com"},
   {"Lubian.com", "lubian.com"},
   {"GBMiners", "mined by gbminers"},
   {"Mt Red", "mtred"},
   {"Pega Pool", "pegapool"},
   {"PHash.IO", "phash.cn"},
   {"PHash.IO", "phash.io"},
   {"21 Inc.", "pool34"},
   {"Poolin", "poolin.com"},
   {"Poolin", "poolin"},
   {"Braiins Pool", "slushpool"},
   {"Braiins Pool", "slush"},
   {"Solo CK", "solo.ckpool.org"},
   {"Ultimus Pool", "ultimus"},
   {"OKExPool", "www.okex.com"},
   {"okpool.top", "www.okpool.top"},
   {"8baochi", "8baochi.com"},
   {"50BTC", "50btc"},
   {"ASICMiner", "asicminer"},
   {"Bitfarms", "bitfarms"},
   {"Mining Squared", "bsquared network"},
   {"Mining Squared", "miningsquared"},
   {"BTC Guild", "btc guild"},
   {"BTCPool (unidentified)", "btcpool"},
   {"BWPool", "bw pool"},
   {"BWPool", "bwpool"},
   {"BitFuFu", "bitfufu"},
   {"BitMinter", "bitminter"},
   {"Bitalo", "bitalo"},
   {"Bitdeer", "bitdeer"},
   {"Bitsolo", "bitsolo pool"},
   {"BlockFills", "blockfillspool"},
   {"CoinLab", "coinlab"},
   {"EclipseMC", "emc"},
   {"Eligius", "eligius"},
   {"F2Pool", "f2pool"},
   {"F2Pool", "discus fish"},
   {"Give Me Coins", "give-me-coins"},
   {"HASHPOOL", "hashpool"},
   {"HHTT", "hhtt"},
   {"Hummerpool", "hummerpool"},
   {"Innopolis Tech", "innopolis"},
   {"KanoPool", "kano"},
   {"KnCMiner", "kncminer"},
   {"KuCoin Pool", "kucoinpool"},
   {"MaxBTC", "maxbtc"},
   {"175btc", "mined by 175btc.com"},
   {"1Hash", "mined by 1hash.com"},
   {"1Hash", "1hash.com"},
   {"MultiCoin.co", "mined by multicoin.co"},
   {"MiningCity", "miningcity"},
   {"Ocean.xyz", "ocean.xyz"},
   {"SecPool", "secpool"},
   {"SpiderPool", "spiderpool"},
   {"TBDice", "tbdice"},
   {"Titan", "titan.io"},
   {"TogetherPool", "togetherpool"},
   {"TripleMining", "triplemining.com"},
   {"TripleMining", "triplemining"},
   {"UKRPool", "ukrpool.com"},
   {"CleanIncentive", "validated with clean energy"},
   {"WhitePool", "whitepool"},
   {"bcpool.io", "bcpool.io"},
   {"Bitcoin Affiliate Network", "bitcoinaffiliatenetwork.com"},
   {"Bitparking", "bitparking"},
   {"BTCServ", "btcserv"},
   {"Polmine", "by polmine.pl"},
   {"Polmine", "bypmneu"},
   {"Cointerra", "cointerra"},
   {"MegaBigPower", "megabigpower.com"},
   {"mmpool", "mmpool"},
   {"myBTCcoin Pool", "mybtccoin pool"},
   {"NMCbit", "nmcbit.com"},
   {"OKMINER", "okminer.com/euz"},
   {"OzCoin", "ozco.in"},
   {"OzCoin", "ozcoin"},
   {"Bitcoin.com", "pool.bitcoin.com"},
   {"simplecoin.us", "simplecoin"},
   {"ST Mining Corp", "st mining corp"},
   {"Terra Pool", "terrapool.io"},
   {"Tiger Pool", "tigerpool.net"},
   {"Tiger Pool", "tiger"},
   {"EXX&BW", "xbtc.exx.com&bw.com"},
   {"Yourbtc.net", "yourbtc.net"},
};

const std::size_t kScriptSigAliasesCount =
   sizeof(kScriptSigAliases) / sizeof(kScriptSigAliases[0]);

constexpr PayoutAlias kPayoutAddressAliases[] = {
   {"11wC5KcbgrWRBb43cwADdVrxgyF8mndVC", "MiningCity"},
   {"122pN8zvqTxJaA8fRY1PDBu4QYodqE5m2X", "Binance Pool"},
   {"125K2xfiBdae42gSKiCGwi85Frpy1vHmGj", "UKRPool"},
   {"125m2H43pwKpSZjLhMQHneuTwTJN5qRyYu", "SpiderPool"},
   {"12KKDt4Mj7N5UAkQMN7LtPZMayenXHa8KL", "Foundry USA"},
   {"12QVFmJH2b4455YUHkMpEnWLeRY3eJ4Jb5", "AAO Pool"},
   {"12Taz8FFXQ3E2AGn3ZW1SZM5bLnYGX4xR6", "Tangpool"},
   {"12cKiMNhCtBhZRUBCnYXo8A4WQzMUtYjmR", "Sigmapool.com"},
   {"12dRugNcdxK39288NjcDV4GX7rMsKCGn6B", "AntPool"},
   {"12znnESiJ3bgCLftwwrg9wzQKN8fJtoBDa", "shawnp0wers"},
   {"13Sd8Y7nUao3z4bJFkZvCRXpFqHvLy49YY", "Telco 214"},
   {"13hQVEstgo4iPQZv9C7VELnLWF7UWtF4Q3", "Bixin"},
   {"13vWXwzNF5Ef9SUXNTdr7de7MqiV4G1gnL", "Polmine"},
   {"147SwRQdpCfj5p8PnfsXV2SsVVpVcz3aPq", "1THash"},
   {"14M1pQ5KKeqmDrmqKyZEnaxAGJfBPrfWvQ", "Telco 214"},
   {"14R2r9FkyDmyxGB9xUVwVLdgsX9YfdVamk", "BitcoinRussia"},
   {"14VkxDwSAUWrzYTxV49HnYhKLWTJ3pCoUS", "WhitePool"},
   {"14hLEtxozmmih6Gg5xrGZLfx51bEMj21NW", "Titan"},
   {"14sA8jqYQgMRQV9zUtGFvpeMEw7YDn77SK", "Poolin"},
   {"14yfxkcpHnju97pecpM7fjuTkVdtbkcfE6", "BitFury"},
   {"151T7r1MhizzJV6dskzzUkUdr7V8JxV2Dx", "myBTCcoin Pool"},
   {"152f1muMCNa7goXYhYAQC61hxEgGacmncB", "BTCC"},
   {"155fzsEBHy9Ri2bMQ8uuuR3tv1YzcDywd4", "BitClub"},
   {"15MdAHnkxt9TMC2Rj595hsg8Hnv693pPBB", "MARA Pool"},
   {"15MxzsutVroEE9XiDckLxUHTCDAEZgPZJi", "BTCDig"},
   {"15kiNKfDWsq7UsPg87UwxA8rVvWAjzRkYS", "AntPool"},
   {"15rQXUSBQRubShPpiJfDLxmwS8ze2RUm4z", "21 Inc."},
   {"15vgygQ7ZsWdvZpctmTZK4673QBHsos6Sh", "1THash"},
   {"15xcAZ2HfaSwYbCV6GGbasBSAekBRRC5Q2", "OKMINER"},
   {"15xiShqUqerfjFdyfgBH1K7Gwp6cbYmsTW", "EclipseMC"},
   {"165GCEAx81wce33FWEnPCRhdjcXCrBJdKn", "BitcoinRussia"},
   {"167ApWWxUSFQmz2jdz9xop3oAKdLejvMML", "BATPOOL"},
   {"16GsNC3q6KgVXkUX7j7aPxSUdHrt1sN2yN", "Eobot"},
   {"16JHXJ7M2MubWNX9grnqbjUqJ5PHwcCWw2", "OKKONG"},
   {"16MdTdqmXusauybtXTmFEW4GNFPPgGxQYE", "AntPool"},
   {"16cv7wyeG6RRqhvJpY21CnsjxuKj2gAoK2", "Polmine"},
   {"16jnC5hVyjk4gE6BJtLqkkyfZHqXCB5PBu", "Polmine"},
   {"16kUc5B48qnASbxeZTisCqTNx6G3DPXuKn", "AntPool"},
   {"16moWjUJVRnDQKqhoCdcszfJg9wzBdoTHw", "Binance Pool"},
   {"17JJ3oZyF4ShQMGukDjpMWhmooCjEvoVVB", "MegaBigPower"},
   {"17gVZssumiJqYMCHozHKXGyaAvyu6NCX6V", "AntPool"},
   {"17judvK4AC2M6KhaBbAEGw8CTKc9Pg8wup", "HotPool"},
   {"17kkmDx8eSwj2JTTULb3HkJhCmexfysExz", "Polmine"},
   {"17tUZLvy3X2557JGhceXRiij2TNYuhRr4r", "Poolin"},
   {"18EPLvrs2UE11kWBB3ABS7Crwj5tTBYPoa", "GoGreenLight"},
   {"18HEMWFXM9UGPVZHUMdBPD3CMFWYn2NPRX", "shawnp0wers"},
   {"18M9o2mXNjNR96yKe7eyY6pfP6Nx4Nso3d", "EclipseMC"},
   {"18Zcyxqna6h7Z7bRjhKvGpr8HSfieQWXqj", "Huobi Pool"},
   {"18ikmzPqk721ZNvWhDos1UL4H29w352Kj5", "Telco 214"},
   {"18xf3MQvdVzKhyRvog8Q5P5THWvSjJUkzf", "MegaBigPower"},
   {"18zRehBcA2YkYvsC7dfQiFJNyjmWvXsvon", "Bitsolo"},
   {"197miJmttpCt2ubVs6DDtGBYFDroxHmvVB", "Patels"},
   {"199EDJoCpqV672qESEkfFgEqNT1iR2gj3t", "58COIN"},
   {"19PkHafEN18mquJ9ChwZt5YEFoCdPP5vYB", "BitMinter"},
   {"19RE4mz2UbDxDVougc6GGdoT4x5yXxwFq2", "Patels"},
   {"19qa95rTbDziNCS9EexUbh2hVY4viUU9tt", "HAOZHUZHU"},
   {"1A32KFEX7JNPmU1PVjrtiXRrTQcesT3Nf1", "MARA Pool"},
   {"1ACAgPuFFidYzPMXbiKptSrwT74Dg8hq2v", "DPOOL"},
   {"1AJQ3jXhUF8WiisEcuVd8Xmfq4QJ7n1SdL", "AntPool"},
   {"1ALA5v7h49QT7WYLcRsxcXqXUqEqaWmkvw", "CloudHashing"},
   {"1AM2fYfpY3ZeMeCKXmN66haoWxvB89pJUx", "DPOOL"},
   {"1AZ6BkCo4zgTuuLpRStJH8iNsehXTMp456", "BitcoinIndia"},
   {"1AajKXkaq2DsnDmP8ZPTrE5gH1HFo1x3AU", "Polmine"},
   {"1AcAj9p6zJn4xLXdvmdiuPCtY7YkBPTAJo", "BitFury"},
   {"1AePMyovoijxvHuKhTqWvpaAkRCF4QswC6", "Tricky's BTC Pool"},
   {"1AfPSq5ZbqBaxU5QAayLQJMcXV8HZt92eq", "Mining-Dutch"},
   {"1Afcpc2FpPnREU6i52K3cicmHdvYRAH9Wo", "CANOE"},
   {"1ApE99VM5RJzMRRtwd2JMgmkGabtJqoMEz", "CKPool"},
   {"1AqTMY7kmHZxBuLUR5wJjPFUvqGs23sesr", "Braiins Pool"},
   {"1ArTPjj6pV3aNRhLPjJVPYoxB98VLBzUmb", "KuCoin Pool"},
   {"1AsEJU4ht5wR7BzV6xsNQpwi5qRx4qH1ac", "Telco 214"},
   {"1BDbsWi3Mrcjp1wdop3PWFNCNZtu4R7Hjy", "EMCDPool"},
   {"1BGFwRzjCfRR7EvRHnzfHyFjGR8XiBDFKa", "Pega Pool"},
   {"1BM1sAcrfV6d4zPKytzziu4McLQDsFC2Qc", "SpiderPool"},
   {"1BRY8AD7vSNUEE75NjzfgiG18mWjGQSRuJ", "UNOMP"},
   {"1BUhwvF9oo3qkaSjjPpWrUzQxXNjkHdMZF", "Telco 214"},
   {"1BWW3pg5jb6rxebrNeo9TATarwJ1rthnoe", "AntPool"},
   {"1BX5YoLwvqzvVwSrdD4dC32vbouHQn2tuF", "Cointerra"},
   {"1Bf9sZvBHPFGVPX71WX2njhd1NXKv5y7v5", "BTC.com"},
   {"1BwZeHJo7b7M2op7VDfYnsmcpXsUYEcVHm", "BTC Nuggets"},
   {"1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE", "Braiins Pool"},
   {"1CNq2FAw6S5JfBiDkjkYJUVNQwjoeY4Zfi", "Telco 214"},
   {"1Ca1KNQQo8akbrwTjjXuk8aikvC2pwodU2", "BTCPool (unidentified)"},
   {"1CdJi2xRTXJF6CEJqNHYyQDNEcM3X7fUhD", "21 Inc."},
   {"1CjPR7Z5ZSyWk6WtXvSFgkptmpoi4UM9BC", "GHash.IO"},
   {"1Cs5RT9SRk1hxsdzivAfkjesNmVVJqfqkw", "EkanemBTC"},
   {"1CyB8GJNEsNVXtPutB36nrDY3fMXBTzXSX", "AntPool"},
   {"1D4UZG4qo8bF1MuZHSEyBHRZaxT8inatXS", "AntPool"},
   {"1DDXyKUT6q3H9e5QXm2Gv6BNNWgztFG55g", "AntPool"},
   {"1DSh7vX6ed2cgTeKPwufV5i4hSi4pp373h", "Binance Pool"},
   {"1DXRoTT67mCbhdHHL1it4J1xsSZHHnFxYR", "Telco 214"},
   {"1Dek9ArRHb9tyWb9gaaX8SWmkfi5V7U5Y6", "AntPool"},
   {"1DyR7HPQWjM6Zrnk7SzHVY2GEpXRGNNH9o", "AntPool"},
   {"1E18BNyobcoiejcDYAz5SjbrzifNDEpM88", "BCMonster"},
   {"1E8CZo2S3CqWg1VZSJNFCTbtT8hZPuQ2kB", "Poolin"},
   {"1EMVSMe1VJUuqv7D7SFzctnVXk4KdjXATi", "Ultimus Pool"},
   {"1EepjXgvWUoRyNvuLSAxjiqZ1QqKGDANLW", "Huobi Pool"},
   {"1EowSPumj9D9AMTpE64Jr7vT3PJDNopVcz", "CKPool"},
   {"1F1xcRt8H8Wa623KqmkEontwAAVqDSAWCV", "1Hash"},
   {"1FFxkVijzvUPUeHgkFjBk2Qw8j3wQY2cDw", "Foundry USA"},
   {"1FLH1SoLv4U68yUERhDiWzrJn5TggMqkaZ", "Waterhole"},
   {"1FdJkPdpXtK3t5utZHJAop3saLZWfPfgak", "AntPool"},
   {"1FeDtFhARLxjKUPPkQqEBL78tisenc9znS", "BitFury"},
   {"1GBo1f2tzVx5jScV9kJXPUP9RjvYXuNzV7", "Nexious"},
   {"1GC6HxDvnchDdb5cGkFXsJMZBFRsKAXfwi", "21 Inc."},
   {"1GNgwA8JfG7Kc8akJ8opdNWJUihqUztfPe", "Poolin"},
   {"1GP8eWArgpwRum76saJS4cZKCHWJHs9PQo", "CanoePool"},
   {"1GRcX882sdBYCAWyG99iF2oz7j3nYzXhLM", "AntPool"},
   {"1GaKSh2t396nfSg5Ku2J3Yn1vfVsXrGuH5", "Telco 214"},
   {"1Gp7iCzDGMZiV55Kt8uKsux6VyoHe1aJaN", "AntPool"},
   {"1H3u6R813MHGYhmGW6v86EYYriawRtACYD", "AntPool"},
   {"1Hk9gD8xMo2XBUhE73y5zXEM8xqgffTB5f", "8baochi"},
   {"1Hz96kJKF2HLPGY15JWLB5m9qGNxvt8tHJ", "BTC.TOP"},
   {"1JBVrhSSDrZrRmm4RnoWouqgGGqJMvWHi8", "AntPool"},
   {"1JLRXD8rjRgQtTS9MvfQALfHgGWau9L9ky", "BWPool"},
   {"1JLc3JxvpdL1g5zoX8sKLP4BkJQiwnJftU", "7pool"},
   {"1JpKmtspBJQVXK67DJP64eBJcAPhDvJ9Er", "RigPool"},
   {"1JrYhdhP2jCY6JwuVzdk9jUwc4pctcSes7", "Polmine"},
   {"1JvXhnHCi6XqcanvrZJ5s2Qiv4tsmm2UMy", "Binance Pool"},
   {"1JwUDWVSbAY5NeCBJhxQk1E8AfETfZuPj4", "AntPool"},
   {"1K7znxRfkS8R1hcmyMvHDum1hAQreS4VQ4", "MegaBigPower"},
   {"1K8PNogxBZ6ts532DZnzxdbjgzJLjLdXqz", "AntPool"},
   {"1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY", "F2Pool"},
   {"1KGG9kvV5zXiqyQAMfY32sGt9eFLMmgpgX", "F2Pool"},
   {"1KGbsDDAgJN2HDNBjmMHp9828qATo5B9c9", "CKPool"},
   {"1KPQkehgYAqwiC6UCcbojM3mbGjURrQJF2", "ConnectBTC"},
   {"1KTNEBhQdj81UhDkJaoe3r8VtAsrnmpmnS", "MegaBigPower"},
   {"1KsFhYKLs8qb1GHqrPxHoywNQpet2CtP9t", "Bixin"},
   {"1LTGvTjDxiy5S9YcKEE9Lb7xSpZcPSqinw", "AntPool"},
   {"1LXWA3EEEwPixQcyFWXKX2hWHpkDoLknZW", "Telco 214"},
   {"1LsFmhnne74EmU4q4aobfxfrWY4wfMVd8w", "Tiger Pool"},
   {"1M1Xw2rczxkF3p3wiNHaTmxvbpZZ7M6vaa", "Poolin"},
   {"1MFsp2txCPwMMBJjNNeKaduGGs8Wi1Ce7X", "A-XBT"},
   {"1MPxhNkSzeTNTHSZAibMaS8HS1esmUL1ne", "Eobot"},
   {"1MeffGLauEj2CZ18hRQqUauTXb9JAuLbGw", "Multipool"},
   {"1MimPd6LrPKGftPRHWdfk8S3KYBfN4ELnD", "digitalBTC"},
   {"1MkCDCzHpBsYQivp8MxjY5AkTGG1f2baoe", "Luxor"},
   {"1MoYfV4U61wqTPTHCyedzFmvf2o3uys2Ua", "Telco 214"},
   {"1MvYASoHjqynMaMnP7SBmenyEWiLsTqoU6", "Huobi Pool"},
   {"1NS4gbx1G2D5rc9PnvVsPys12nKxGiQg72", "AntPool"},
   {"1NY15MK947MLzmPUa2gL7UgyR8prLh2xfu", "digitalX Mintsy"},
   {"1Nd99aNgYWpKkqcqSMgWtdtVDadewAS5F7", "BitFury"},
   {"1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB", "AntPool"},
   {"1Nsvmnv8VcTMD643xMYAo35Aco3XA5YPpe", "Polmine"},
   {"1P4B6rx1js8TaEDXvZvtrkiEb9XrJgMQ19", "Telco 214"},
   {"1PtT8a79X2CbFSqwX2nCZjrvqaGRgfLxbz", "Poolin"},
   {"1PuJjnF476W3zXfVYmJfGnouzFDAXakkL4", "ViaBTC"},
   {"1PzVut5X6Nx7Mv4JHHKPtVM9Jr9LJ4Rbry", "BlockFills"},
   {"1QEiAhdHdMhBgVbDM7zUXWGkNhgEEJ6uLd", "ArkPool"},
   {"1Sjj2cPC3rTWcSTEYDeu2f3BavLosog4T", "AntPool"},
   {"1jKSjMLnDNup6NPgCjveeP9tUn4YpT94Y", "BTCMP"},
   {"1jLVpwtNMfXWaHY4eiLDmGuBxokYLgv1X", "AntPool"},
   {"1qtKetXKgqa7j1KrB19HbvfRiNUncmakk", "transactioncoinmining"},
   {"32BfKjhByDSxx3BM5vUkQ3NQq9csZR6nt6", "Luxor"},
   {"32P5KVSbZYAkVmSHxDd2oBXaSk372rbV7L", "Terra Pool"},
   {"33SAB6pzbhEGPbfY6NVgRDV7jVfspZ3A3Z", "Carbon Negative (unidentified)"},
   {"33TbzA5AMiTKUCmeVEdsnTj3GiVXuavCAH", "Poolin"},
   {"34Jpa4Eu3ApoPVUKNTN2WeuXVVq1jzxgPi", "Lubian.com"},
   {"34qkc2iac6RsyxZVfyE2S5U5WcRsbg2dpK", "BTC.com"},
   {"35qGBQsRQb8CSUzcSWktMykeA6zm5iCEJJ", "Poolin"},
   {"35y82tEPDa2wm6tzkEacMG8GPPW7zbMj83", "Rawpool"},
   {"36cWgjEtxQSFgbHTJDw5AB96ZX7fJk1URd", "BTC.com"},
   {"36n452uGq1x4mK7bfyZR8wgE47AnBb2pzi", "Poolin"},
   {"36r3YqAXWpyqNcczjCBdHrYZ3m8X56WDzx", "MaxiPool"},
   {"38u1srayb1oybVB43UWKBJsrwJbdHGtPx2", "SpiderPool"},
   {"39C7fxSzEACPjM78Z7xdPxhf7mKxJwvfMJ", "AntPool"},
   {"39bitUyBcUu3y3hRTtYprKbTp712t4ZWqK", "Luxor"},
   {"39m5Wvn9ZqyhYmCYpsyHuGMt5YYw4Vmh1Z", "BytePool"},
   {"3A2dwyVPbZc41vvmJVYxYsrkvNKnz2B4wN", "Poolin"},
   {"3Awm3FNpmwrbvAFVThRUFqgpbVuqWisni9", "SecPool"},
   {"3Bmb9Jig8A5kHdDSxvDZ6eryj3AXd3swuJ", "NovaBlock"},
   {"3C9sAKXrBVpJVe3b738yik4LPHpPmceBgd", "Ultimus Pool"},
   {"3CLigLYNkrtoNgNcUwTaKoUSHCwr9W851W", "Rawpool"},
   {"3D72db1KMCnj7FL7MBsmxTw81z2bVu4UN5", "MARA Pool"},
   {"3DXfeMBimuvN3TWnQXDhr47P8M8yxMy9Pd", "Poolin"},
   {"3EhLZarJUNSfV6TWMZY1Nh5mi3FMsdHa5U", "BTC.com"},
   {"3G7jcEELKh38L6kaSV8K35pTqsh5bgZW2D", "Binance Pool"},
   {"3GdjWJdkJhtkxRZ3Ns1LstaoHNMBW8XsvU", "Mining Squared"},
   {"3GvEGtnvgeBJ3p3EpdZhvUkxY4pDARkbjd", "Bitfarms"},
   {"3HuobiNg2wHjdPU2mQczL9on8WF7hZmaGd", "Huobi Pool"},
   {"3JP3zF7LoeoAotqkNGdvX5szUyNPwd937d", "BitFuFu"},
   {"3JQSigWTCHyBLRD979JWgEtWP5YiiFwcQB", "Poolin"},
   {"3KJrsjfg1dD6CrsTeHdHVH3KqMpvL2XWQn", "Poolin"},
   {"3KZDwmJHB6QJ13QPXHaW7SS3yTESFPZoxb", "Carbon Negative (unidentified)"},
   {"3L8Ck6bm3sve1vJGKo6Ht2k167YKSKi8TZ", "Binance Pool"},
   {"3LC8dDKyBsrWPfzhXyt7aAyjXxGYkfDdHu", "MARA Pool"},
   {"3NA8hsjfdgVkmmVS9moHmkZsVCoLxUkvvv", "BTC.com"},
   {"3P8sR3K8wAk3bom7tqpr5VrzCz9TVYNTQd", "CKPool"},
   {"3QLeXx1J9Tp3TBnQyHrhVxne9KqkAS9JSR", "CN/TT"},
   {"3QYvfQoG9Gs9Vfvbpw6947muSqhoGagvF6", "Rawpool"},
   {"3Qqp7LwxmSjPwRaKkDToysJsM3xA4ThqFk", "Terra Pool"},
   {"bc1q75t4wewkmf3l9qg097zvtlh05v5pdz6699kv8k", "Innopolis Tech"},
   {"bc1q7wedv4zdu5smt3shljpu5mgns48jn299mukymc", "F2Pool"},
   {"bc1qf274x7penhcd8hsv3jcmwa5xxzjl2a6pa9pxwm", "F2Pool"},
   {"bc1qjl8uwezzlech723lpnyuza0h2cdkvxvh54v3dn", "BTC.com"},
   {"bc1qrm09asqsxh2l7pjxjlltm53tx689dp2amzupzq", "CleanIncentive"},
   {"bc1qvfzssz36y4gxcg9gh234rzem9k0vrdlx4kq5sg", "NiceHash"},
   {"bc1qwlrsvgtn99rqp3fgaxq6f6jkgms80rnej0a8tc", "TogetherPool"},
   {"bc1qwzrryqr3ja8w7hnja2spmkgfdcgvqwp5swz4af4ngsjecfz0w0pqud7k38",
    "Foundry USA"},
   {"bc1qx9t2l3pyny2spqpqlye8svce70nppwtaxwdrp4", "Binance Pool"},
};

const std::size_t kPayoutAddressAliasesCount =
   sizeof(kPayoutAddressAliases) / sizeof(kPayoutAddressAliases[0]);

